kind: PersistentVolume
apiVersion: v1
metadata:
  name: wp-mysql-pv
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/sanjay_kathiriya/mysql"
